python CSPStowage.py ./CSP-tests mapa.txt contenedores.txt
python CSPStowage.py ./CSP-tests mapa1.txt contenedores1.txt
python CSPStowage.py ./CSP-tests mapa2.txt contenedores2.txt
python CSPStowage.py ./CSP-tests mapa3.txt contenedores3.txt
python CSPStowage.py ./CSP-tests mapa4.txt contenedores4.txt
python CSPStowage.py ./CSP-tests mapa5.txt contenedores5.txt
python CSPStowage.py ./CSP-tests mapa6.txt contenedores6.txt
python CSPStowage.py ./CSP-tests mapa7.txt contenedores7.txt
python CSPStowage.py ./CSP-tests mapa8.txt contenedores8.txt